name: dmri_seg
channels:
  - defaults
  - conda-forge
  - pnlbwh
dependencies:
  - ants
  - tensorflow-gpu==1.12.0
  - python==3.6
  - cudatoolkit==9.0
  - keras==2.2.4
  - pip
  - nibabel[version='>=2.2.1']
  - cudnn==7.6.0
  - s3path
